### ISSUE TITLE
Shared ownership of fences

### ISSUE THREAD

**Issue by mothbooty** [OpenModularTurretsTeam/OpenModularPassiveDefense#7]
Was wondering if you could add a feature to allow multiple people to be safe from the fences, like the permitted players list of the modular turrets.

**Comment by hanakocz** [comment]
THis could be done via some Security block, which you would be able to open and type UUIDs (names) in it (and after they get checked (probably against server's list of player profiles or something), then it will store this value for the owner somewhere...and then when player touches the fence, it won't check if he is owner, but if he is on owner's trustlist (where the owner will always be). 
That way can be easy and also no more checks , because you already do one check if the player is owner.

**Comment by Keridos** [comment]
No need for a security block, I can probably just add a command that does exactly that, will be included in OMLib in the future (would also affect turret bases from OMT that way)

**Comment by kreezxil** [comment]
Since you guys are working on the opencomputers/turret issue and I agree I thought it weird that my friend got hurt when touching the fence too, can you please add this.

**Comment by Keridos** [comment]
I am working on this, it is a bit more code than i originally though, but in a few releases we might have that.

**Comment by Keridos** [comment]
Fixed in latest omlib builds.

**Comment by hanakocz** [comment]
We will test this out as soon as we get it on server updated, thanks for good job on that. However one more question. Can be player's pets included in it? For example if you tame wolf or cat, that they would not get damage? It should not be that hard probably, as each of those tamed pets have some player as owner. (if not spawned as tamed, but with tamed owner empty NBT). Those pets are really dumb sometimes when something attacks you :)

**Comment by Keridos** [comment]
We can add a check for that, both in OMPD and OMT
